name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Get Repo
      uses: actions/checkout@v2

    - name: Get Node
      uses: actions/setup-node@v2
      with:
        node-version: "16.14.2"

    - name: Deploy
      run: |
        cd ronni*
        npm install
        npm run deploy
      
